### ISSUE TITLE
博主您好，想请问下关于linux系统使用这份代码的问题

### ISSUE THREAD

**Issue by O-Givenchy** [shillyshallysxy/emotion_classifier#1]
博主您好；

我想请问一个问题，

若是我想在ubuntu上使用这份代码，那有些什么地方是需要修改和注意的吗？  

期待您的回复，谢谢~

**Comment by xingyu-shi** [comment]
你好， 映像中没有使用win的组件，但没在linux上测试过，可以试试，应该不会有太多问题------------------ 原始邮件 ------------------
发件人: "Cyrus"<notifications@github.com>
发送时间: 2019年4月26日(星期五) 上午10:01
收件人: "shillyshallysxy/emotion_classifier"<emotion_classifier@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)



博主您好；
 
我想请问一个问题，
 
若是我想在ubuntu上使用这份代码，那有些什么地方是需要修改和注意的吗？
 
期待您的回复，谢谢~
 
&mdash;

**Comment by O-Givenchy** [comment]
> 你好， 映像中没有使用win的组件，但没在linux上测试过，可以试试，应该不会有太多问题------------------ 原始邮件 ------------------
> 发件人: "Cyrus"<notifications@github.com>
> 发送时间: 2019年4月26日(星期五) 上午10:01
> 收件人: "shillyshallysxy/emotion_classifier"<emotion_classifier@noreply.github.com>;
> 抄送: "Subscribed"<subscribed@noreply.github.com>;
> 主题: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)
> 
> 
> 
> 博主您好；
> 
> 我想请问一个问题，
> 
> 若是我想在ubuntu上使用这份代码，那有些什么地方是需要修改和注意的吗？
> 
> 期待您的回复，谢谢~
> 
> &mdash;
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

谢谢您的回复博主

我打算在ubuntu上试一试

btw，方便说一下您在win10实验的具体环境吗？ 比如python、tensorflow、cuda、cudnn、opencv等相关重要依赖的版本号之类的？

谢谢~ :)

**Comment by xingyu-shi** [comment]
Tensorflow1.12.0  低于1.11.0可能会报handle部分的错误 Python3.6  python 3应该都行 Cuda9 ------------------ 原始邮件 ------------------
发件人: "Cyrus"<notifications@github.com>
发送时间: 2019年4月26日(星期五) 上午10:37
收件人: "shillyshallysxy/emotion_classifier"<emotion_classifier@noreply.github.com>;
抄送: "shillyshallysxy"<895484721@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)


 
你好， 映像中没有使用win的组&#x4EF6;，但没在linux上测试过，可以试试，应该不会有太多问题------------------ 原始邮&#x4EF6; ------------------
 发&#x4EF6;人: "Cyrus"notifications@github.com
 发送时间: 2019年4月26日(星期五) 上午10:01
 收&#x4EF6;人: "shillyshallysxy/emotion_classifier"emotion_classifier@noreply.github.com;
 抄送: "Subscribed"subscribed@noreply.github.com;
 主题: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)
 
博主您好；
 
我想请问一个问题，
 
若是我想在ubuntu上使用这份代码，那有些什么地方是需要修改和注意的吗？
 
期待您的回复，谢谢~
 
—
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or mute the thread.
  
谢谢您的回复博主
 
我打算在ubuntu上试一试
 
btw，方便说一下您在win10实验的具体环境吗？ 比如python、tensorflow、cuda、cudnn、opencv等相关重要依赖的版本号之类的？
 
&mdash;

**Comment by O-Givenchy** [comment]
> Tensorflow1.12.0  低于1.11.0可能会报handle部分的错误 Python3.6  python 3应该都行 Cuda9 ------------------ 原始邮件 ------------------
> 发件人: "Cyrus"<notifications@github.com>
> 发送时间: 2019年4月26日(星期五) 上午10:37
> 收件人: "shillyshallysxy/emotion_classifier"<emotion_classifier@noreply.github.com>;
> 抄送: "shillyshallysxy"<895484721@qq.com>;"Comment"<comment@noreply.github.com>;
> 主题: Re: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)
> 
> 
> 
> 你好， 映像中没有使用win的组&#x4EF6;，但没在linux上测试过，可以试试，应该不会有太多问题------------------ 原始邮&#x4EF6; ------------------
>  发&#x4EF6;人: "Cyrus"notifications@github.com
>  发送时间: 2019年4月26日(星期五) 上午10:01
>  收&#x4EF6;人: "shillyshallysxy/emotion_classifier"emotion_classifier@noreply.github.com;
>  抄送: "Subscribed"subscribed@noreply.github.com;
>  主题: [shillyshallysxy/emotion_classifier] 博主您好，想请问下关于linux系统使用这份代码的问题 (#1)
> 
> 博主您好；
> 
> 我想请问一个问题，
> 
> 若是我想在ubuntu上使用这份代码，那有些什么地方是需要修改和注意的吗？
> 
> 期待您的回复，谢谢~
> 
> —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 谢谢您的回复博主
> 
> 我打算在ubuntu上试一试
> 
> btw，方便说一下您在win10实验的具体环境吗？ 比如python、tensorflow、cuda、cudnn、opencv等相关重要依赖的版本号之类的？
> 
> &mdash;
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

好的。。谢谢博主~~ 到时候要还有些其他什么问题，还需麻烦您帮我解答一下哈~。。。
